type ThemeColorsKey =
| 'background'
| 'foreground'
| 'card'
| 'cardForeground'
| 'popover'
| 'popoverForeground'
| 'primary'
| 'primaryForeground'
| 'secondary'
| 'secondaryForeground'
| 'muted'
| 'mutedForeground'
| 'accent'
| 'accentForeground'
| 'destructive'
| 'border'
| 'input'
| 'ring'
| 'chart1'
| 'chart2'
| 'chart3'
| 'chart4'
| 'chart5'
| 'sidebar'
| 'sidebarForeground'
| 'sidebarPrimary'
| 'sidebarPrimaryForeground'
| 'sidebarAccent'
| 'sidebarAccentForeground'
| 'sidebarBorder'
| 'sidebarRing';

export type ThemeColorsType = Record<ThemeColorsKey, string>;

