/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ThemeConfigRouteImport } from './routes/theme-config.route'
import { Route as HomeRouteImport } from './routes/home.route'
import { Route as AboutRouteImport } from './routes/about.route'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const ThemeConfigRouteRoute = ThemeConfigRouteImport.update({
  id: '/theme-config',
  path: '/theme-config',
  getParentRoute: () => rootRoute,
} as any)

const HomeRouteRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRoute,
} as any)

const AboutRouteRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRoute
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRoute
    }
    '/theme-config': {
      id: '/theme-config'
      path: '/theme-config'
      fullPath: '/theme-config'
      preLoaderRoute: typeof ThemeConfigRouteImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteRoute
  '/home': typeof HomeRouteRoute
  '/theme-config': typeof ThemeConfigRouteRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteRoute
  '/home': typeof HomeRouteRoute
  '/theme-config': typeof ThemeConfigRouteRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRouteRoute
  '/home': typeof HomeRouteRoute
  '/theme-config': typeof ThemeConfigRouteRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/home' | '/theme-config'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/home' | '/theme-config'
  id: '__root__' | '/' | '/about' | '/home' | '/theme-config'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRouteRoute: typeof AboutRouteRoute
  HomeRouteRoute: typeof HomeRouteRoute
  ThemeConfigRouteRoute: typeof ThemeConfigRouteRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRouteRoute: AboutRouteRoute,
  HomeRouteRoute: HomeRouteRoute,
  ThemeConfigRouteRoute: ThemeConfigRouteRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/home",
        "/theme-config"
      ]
    },
    "/": {
      "filePath": "index.ts"
    },
    "/about": {
      "filePath": "about.route.tsx"
    },
    "/home": {
      "filePath": "home.route.tsx"
    },
    "/theme-config": {
      "filePath": "theme-config.route.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
